version: "3.8"

services: 
  server:
    platform: linux/x86_64
    build:
    # since this particuler dockerfile is coping files from the host machine
      context: .
      dockerfile: setup/server.dockerfile
    ports: 
      - 8888:80
    # volumes: 
    #   - ./src:/var/www/html
    #   - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: setup/php.dockerfile
    # Commented because we are preparing for deployment
    # volumes:
    #   - ./src:/var/www/html:delegated
    # :delegated referes as optimization for file system changes
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - ./env/mysql.env
# Utility containers:
  composer:
    build: 
      context: ./setup
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  
  artisan:
    build: 
      context: .
      dockerfile: setup/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    image: node:20-alpine
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
