version: "3.8"

services: 
  server:
    image: arm64v8/nginx:stable-alpine
    ports: 
      - 8080:80
    volumes: 
      - ./src:/var/www/html
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

  php:
    build:
      context: ./setup
      dockerfile: php.dockerfile
    volumes:
    # :delegated referes as optimization for file system changes
      - ./src:/var/www/html:delegated
    networks:
      - app-network

  mysql:
    image: arm64v8/mysql
    env_file:
      - ./env/mysql.env
    networks:
      - app-network

  composer:
    build: 
      context: ./setup
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  # artisan:
  # npm:

networks:
  app-network:
    driver: bridge
