version: "3.8"

services: 
  server:
    platform: linux/x86_64
    image: 'nginx:stable-alpine'
    ports: 
      - 8888:80
    volumes: 
      - ./src:/var/www/html
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./setup
      dockerfile: php.dockerfile
    volumes:
    # :delegated referes as optimization for file system changes
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - ./env/mysql.env

  composer:
    build: 
      context: ./setup
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  
  artisan:
    build: 
      context: ./setup
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    image: node:20-alpine
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
