version: "3.8"

services: 
  server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8080:80'
    volumes: 
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    build:
      context: ./setup
      dockerfile: php.dockerfile
    volumes:
    # :delegated referes as optimization for file system changes
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  # composer:
  # artisan:
  # npm: